# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([7, 0, 4, 7, 5, 5, 2, 0, 4, 3])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[ 5, 15, 39, 27, 59],
       [40, 60,  2,  1, 25],
       [20, 99, 92, 69,  6],
       [43,  9, 51, 13,  3]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.71517927, 0.11934345, 0.37419275, 0.18431912, 0.37012774],
        [0.45408719, 0.35886428, 0.55082824, 0.10880826, 0.45550251],
        [0.9438067 , 0.09414388, 0.01513842, 0.80301418, 0.33230018],
        [0.04313263, 0.68834246, 0.23020222, 0.42856374, 0.13754134]],

       [[0.17469855, 0.40611748, 0.9845105 , 0.09839871, 0.4026884 ],
        [0.83839567, 0.47877381, 0.73247327, 0.81165329, 0.33279839],
        [0.18347244, 0.54201051, 0.69079351, 0.81673542, 0.8908374 ],
        [0.36463387, 0.48119906, 0.52400048, 0.89400901, 0.9373762 ]],

       [[0.93124149, 0.96049484, 0.72806895, 0.41062518, 0.69230775],
        [0.93866038, 0.58570041, 0.71947125, 0.49946889, 0.0502934 ],
        [0.65347459, 0.23207609, 0.26435799, 0.93916354, 0.51796314],
        [0.77189226, 0.52296284, 0.16426294, 0.21003054, 0.12094852]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int32')

In [21]:
a1D.dtype.name

'int32'

In [22]:
a2D.dtype

dtype('int32')

In [23]:
a2D.dtype.name

'int32'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'