# Indexação e fatiamento (slicing)

In [2]:
# Importando o NumPy
import numpy as np

In [38]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 7, 10)
a1D

array([2, 4, 2, 6, 6, 3, 4, 2, 5, 1])

In [39]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[ 21,  33,   1,  67,  36],
       [ 58,  37,   7,  79,  72],
       [ 85,  40,  66, 100,  76],
       [ 74,  29,  25,  33,  86]])

In [44]:
print(a1D[9:0:-1])

[1 5 2 4 3 6 6 2 4]


In [5]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.9459895 , 0.29722879, 0.36391998, 0.35233923, 0.91055695],
        [0.57347401, 0.99867774, 0.3952632 , 0.17657821, 0.63789801],
        [0.29783088, 0.97740494, 0.92035062, 0.40383891, 0.74990408],
        [0.52465286, 0.78691623, 0.05630136, 0.88810119, 0.75039326]],

       [[0.1430665 , 0.89152353, 0.46271407, 0.73270075, 0.35227474],
        [0.31396139, 0.6200937 , 0.63737889, 0.33273912, 0.51316509],
        [0.47354131, 0.02857465, 0.8567971 , 0.85191328, 0.91202666],
        [0.98587684, 0.80460851, 0.65849036, 0.56554958, 0.08046657]],

       [[0.57807412, 0.02116458, 0.94799201, 0.56463619, 0.230198  ],
        [0.81891939, 0.33011212, 0.2738273 , 0.85445452, 0.2627451 ],
        [0.0078894 , 0.22018425, 0.88129689, 0.86722047, 0.56794722],
        [0.50373537, 0.56142635, 0.85987865, 0.17291011, 0.64538935]]])

In [60]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)

In [61]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Acessando elementos específicos

In [62]:
A[1]

array([ 6,  7,  8,  9, 10])

In [53]:
linha

NameError: name 'linha' is not defined

In [6]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([7, 2, 3, 4, 6, 6, 4, 5, 2, 8])

In [7]:
# nome_do_array[índice]
a1D[0]

7

In [8]:
a1D[2]

3

In [9]:
a1D[-1]

8

In [10]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([4, 7, 8])

In [11]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[39, 58, 61, 34, 88],
       [49, 98, 40, 13, 50],
       [ 9,  9, 12, 64, 13],
       [95, 64, 55, 67,  2]])

In [12]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

40

In [13]:
a2D[3][4]

2

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([39, 98, 12, 67])

In [15]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([34, 40,  9, 95])

In [16]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([67, 12, 98, 39])

In [17]:
a2D[:,[0,1,2,0]] 

array([[39, 58, 61, 39],
       [49, 98, 40, 49],
       [ 9,  9, 12,  9],
       [95, 64, 55, 95]])

In [19]:
a2D

array([[39, 58, 61, 34, 88],
       [49, 98, 40, 13, 50],
       [ 9,  9, 12, 64, 13],
       [95, 64, 55, 67,  2]])

In [21]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[49, 98, 40, 49],
       [39, 58, 61, 39],
       [49, 98, 40, 49],
       [39, 58, 61, 39]])

In [24]:
a2D

array([[39, 58, 61, 34, 88],
       [49, 98, 40, 13, 50],
       [ 9,  9, 12, 64, 13],
       [95, 64, 55, 67,  2]])

In [33]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[49, 98, 40, 49],
       [39, 58, 61, 39],
       [49, 98, 40, 49],
       [39, 58, 61, 39]])

In [18]:
a2D

array([[80, 78, 37, 15, 68],
       [65,  8, 37, 25, 87],
       [86, 33, 99, 92, 91],
       [57, 30, 98, 62, 13]])

In [19]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[65,  8, 37, 65],
       [80, 78, 37, 80],
       [65,  8, 37, 65],
       [80, 78, 37, 80]])

In [1]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

NameError: name 'a2D' is not defined

In [20]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.09930567, 0.15977358, 0.69541207, 0.47663433, 0.56743545],
        [0.78196052, 0.78084053, 0.64706246, 0.27837311, 0.18811584],
        [0.52177986, 0.21795199, 0.95207306, 0.1748979 , 0.52594386],
        [0.59219297, 0.54167605, 0.50996981, 0.63986999, 0.98218286]],

       [[0.58583563, 0.39808812, 0.68492725, 0.95370417, 0.09473167],
        [0.61333828, 0.04343477, 0.23133131, 0.89743856, 0.70160719],
        [0.97889995, 0.57087873, 0.28006542, 0.50136077, 0.79897494],
        [0.66090173, 0.03261259, 0.92168146, 0.75616825, 0.06013783]],

       [[0.37373338, 0.04872275, 0.18900533, 0.03171578, 0.26366703],
        [0.50125562, 0.85227816, 0.39392428, 0.0394613 , 0.23201446],
        [0.77407251, 0.08005721, 0.31138246, 0.18844529, 0.41473302],
        [0.05526004, 0.46757017, 0.28134351, 0.85562704, 0.23367207]]])

In [21]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.031715777512321686

In [22]:
a3D[0][3][1]

0.5416760496239152

### Fatiamento (slicing)

In [23]:
# Array de 1 dimensão
a1D

array([2, 5, 3, 7, 4, 3, 1, 9, 6, 8])

In [24]:
a = a1D[1:5] # Índice 1 ao 4
a

array([5, 3, 7, 4])

In [25]:
b = a1D[0:6] # Índice 0 ao 5
b

array([2, 5, 3, 7, 4, 3])

In [26]:
c = a1D[:6] # Do início ao 5
c

array([2, 5, 3, 7, 4, 3])

In [27]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([2, 3, 4, 1, 6])

In [28]:
e = a1D[-1::-1] # Do final até o início
e

array([8, 6, 9, 1, 3, 4, 7, 3, 5, 2])

In [29]:
# Array de 2 dimensões
a2D

array([[80, 78, 37, 15, 68],
       [65,  8, 37, 25, 87],
       [86, 33, 99, 92, 91],
       [57, 30, 98, 62, 13]])

In [30]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([80, 78, 37, 15, 68])

In [31]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([65,  8, 37, 25, 87])

In [32]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([33, 99, 92])

In [33]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([57, 30, 98, 62, 13])

In [34]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([37, 37, 99, 98])

In [35]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([25, 92, 62])

In [36]:
# Array de 3 dimensões
a3D

array([[[0.09930567, 0.15977358, 0.69541207, 0.47663433, 0.56743545],
        [0.78196052, 0.78084053, 0.64706246, 0.27837311, 0.18811584],
        [0.52177986, 0.21795199, 0.95207306, 0.1748979 , 0.52594386],
        [0.59219297, 0.54167605, 0.50996981, 0.63986999, 0.98218286]],

       [[0.58583563, 0.39808812, 0.68492725, 0.95370417, 0.09473167],
        [0.61333828, 0.04343477, 0.23133131, 0.89743856, 0.70160719],
        [0.97889995, 0.57087873, 0.28006542, 0.50136077, 0.79897494],
        [0.66090173, 0.03261259, 0.92168146, 0.75616825, 0.06013783]],

       [[0.37373338, 0.04872275, 0.18900533, 0.03171578, 0.26366703],
        [0.50125562, 0.85227816, 0.39392428, 0.0394613 , 0.23201446],
        [0.77407251, 0.08005721, 0.31138246, 0.18844529, 0.41473302],
        [0.05526004, 0.46757017, 0.28134351, 0.85562704, 0.23367207]]])

In [37]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.58583563, 0.39808812, 0.68492725, 0.95370417, 0.09473167],
       [0.61333828, 0.04343477, 0.23133131, 0.89743856, 0.70160719],
       [0.97889995, 0.57087873, 0.28006542, 0.50136077, 0.79897494],
       [0.66090173, 0.03261259, 0.92168146, 0.75616825, 0.06013783]])

In [38]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.39808812, 0.68492725, 0.95370417],
       [0.04343477, 0.23133131, 0.89743856],
       [0.57087873, 0.28006542, 0.50136077]])

In [39]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.52177986, 0.21795199, 0.95207306, 0.1748979 , 0.52594386])

In [40]:
a3D

array([[[0.09930567, 0.15977358, 0.69541207, 0.47663433, 0.56743545],
        [0.78196052, 0.78084053, 0.64706246, 0.27837311, 0.18811584],
        [0.52177986, 0.21795199, 0.95207306, 0.1748979 , 0.52594386],
        [0.59219297, 0.54167605, 0.50996981, 0.63986999, 0.98218286]],

       [[0.58583563, 0.39808812, 0.68492725, 0.95370417, 0.09473167],
        [0.61333828, 0.04343477, 0.23133131, 0.89743856, 0.70160719],
        [0.97889995, 0.57087873, 0.28006542, 0.50136077, 0.79897494],
        [0.66090173, 0.03261259, 0.92168146, 0.75616825, 0.06013783]],

       [[0.37373338, 0.04872275, 0.18900533, 0.03171578, 0.26366703],
        [0.50125562, 0.85227816, 0.39392428, 0.0394613 , 0.23201446],
        [0.77407251, 0.08005721, 0.31138246, 0.18844529, 0.41473302],
        [0.05526004, 0.46757017, 0.28134351, 0.85562704, 0.23367207]]])

In [41]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.78196052, 0.78084053, 0.64706246, 0.27837311, 0.18811584],
       [0.61333828, 0.04343477, 0.23133131, 0.89743856, 0.70160719],
       [0.50125562, 0.85227816, 0.39392428, 0.0394613 , 0.23201446]])

In [42]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.47663433, 0.27837311, 0.1748979 , 0.63986999],
       [0.95370417, 0.89743856, 0.50136077, 0.75616825],
       [0.03171578, 0.0394613 , 0.18844529, 0.85562704]])

### Indexação com booleanos

In [43]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[447,  32,   4,  63, 122, 416,  50,  73],
       [347, 180, 488,  37, 441, 335, 468, 432],
       [ 75,  42,  78, 457, 340,  16,  40, 341],
       [214,  35,  51, 414,  37,  77, 324, 476],
       [215,  34,  13, 211, 274, 205, 425, 479],
       [ 81, 139,  97, 222, 301, 403, 281,  46],
       [ 62,  35,  60, 389, 237, 395, 321, 325],
       [413, 194, 221, 482, 276,  71, 338,  72],
       [310, 122, 162, 339, 234, 263,  29,  39],
       [ 13, 116,  59, 295,  54, 360, 438,  88]])

In [44]:
a2D >= 250

array([[ True, False, False, False, False,  True, False, False],
       [ True, False,  True, False,  True,  True,  True,  True],
       [False, False, False,  True,  True, False, False,  True],
       [False, False, False,  True, False, False,  True,  True],
       [False, False, False, False,  True, False,  True,  True],
       [False, False, False, False,  True,  True,  True, False],
       [False, False, False,  True, False,  True,  True,  True],
       [ True, False, False,  True,  True, False,  True, False],
       [ True, False, False,  True, False,  True, False, False],
       [False, False, False,  True, False,  True,  True, False]])

In [45]:
a2D[a2D >= 250]

array([447, 416, 347, 488, 441, 335, 468, 432, 457, 340, 341, 414, 324,
       476, 274, 425, 479, 301, 403, 281, 389, 395, 321, 325, 413, 482,
       276, 338, 310, 339, 263, 295, 360, 438])

In [46]:
a2D.mean()

214.875

In [47]:
a2D[a2D <= a2D.mean()]

array([ 32,   4,  63, 122,  50,  73, 180,  37,  75,  42,  78,  16,  40,
       214,  35,  51,  37,  77,  34,  13, 211, 205,  81, 139,  97,  46,
        62,  35,  60, 194,  71,  72, 122, 162,  29,  39,  13, 116,  59,
        54,  88])