# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [2]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([ 90,  63,  33, 142,  59, 199, 173, 156, 198, 195, 185, 104])

In [3]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[124,  67, 192,  81],
       [155,   1, 126,  48],
       [131,  96,  74,  54]])

In [4]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[147,  34, 188, 188, 177,  88],
        [118,  98,  76, 113, 164,  86],
        [108,  25, 129, 177,  68,   5]],

       [[ 34,  51,  39, 181, 173,  96],
        [ 58,  21,  20,  25,  30, 103],
        [  9,  99, 122, 140,   8,   3]]])

In [5]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1,  63,  33, 142,  59, 199, 173, 156, 198, 195, 185, 104])

In [6]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[124,  67, 192,  81],
       [155,   1,  -1,  48],
       [131,  96,  74,  54]])

In [7]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[147,  34, 188, 188, 177,  88],
        [118,  98,  76, 113, 164,  86],
        [108,  25, 129, 177,  68,   5]],

       [[ 34,  51,  39, 181, 173,  96],
        [ 58,  21,  20,  25,  30, 103],
        [  9,  99, 122, 140,  -1,   3]]])

In [8]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
a1D_modificado

array([ -1,  63,  33, 142,  59, 199, 173, 156, 198, 195, 185, 104, 100,
       130])

In [9]:
a1D # a1D não foi modificado

array([ -1,  63,  33, 142,  59, 199, 173, 156, 198, 195, 185, 104])

In [10]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([124,  67, 192,  81, 155,   1,  -1,  48, 131,  96,  74,  54, 100,
       130])

In [11]:
a2D # a2D não foi modificado

array([[124,  67, 192,  81],
       [155,   1,  -1,  48],
       [131,  96,  74,  54]])

In [12]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([147,  34, 188, 188, 177,  88, 118,  98,  76, 113, 164,  86, 108,
        25, 129, 177,  68,   5,  34,  51,  39, 181, 173,  96,  58,  21,
        20,  25,  30, 103,   9,  99, 122, 140,  -1,   3, 100, 130])

In [13]:
a3D # a3D não foi modificado

array([[[147,  34, 188, 188, 177,  88],
        [118,  98,  76, 113, 164,  86],
        [108,  25, 129, 177,  68,   5]],

       [[ 34,  51,  39, 181, 173,  96],
        [ 58,  21,  20,  25,  30, 103],
        [  9,  99, 122, 140,  -1,   3]]])

In [14]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1  63  33 142  59 199 173 156 198 195 185 104 100 130]
[ 33  59 199 173 156 198 195 185 104 100 130]


### Comparação entre arrays

In [15]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [16]:
c1D = np.random.randint(1,10,20)
c1D

array([5, 2, 1, 7, 1, 6, 8, 3, 2, 3, 1, 4, 3, 7, 5, 7, 1, 2, 2, 5])

In [17]:
c1D == 5

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False,  True])

In [18]:
c1D[c1D == 5]

array([5, 5, 5])

### Operações entre arrays e escalares

In [19]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [23]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [25]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [26]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [27]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [28]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [29]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [30]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [31]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [32]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [33]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [34]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [35]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [36]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
raiz1D = np.sqrt(g1D)
raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

In [38]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[43, 16, 44, 79,  6, 85, 71, 14, 80,  3],
       [19, 17,  5, 24, 10, 93, 71, 30, 50, 42],
       [17, 78,  6,  5, 10, 31, 58, 18, 63, 38],
       [59, 22, 89, 93,  5, 14, 45, 32, 26, 21],
       [18, 65,  9, 16, 31, 33, 94, 40, 36, 88]])

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [39]:
# Soma de todos os elementos
d2D.sum()

1962

In [40]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([156, 198, 153, 217,  62, 256, 339, 134, 255, 192])

In [41]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([441, 361, 324, 406, 430])

In [42]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([156, 198, 153, 217,  62, 256, 339, 134, 255, 192])

In [43]:
# Retorna o menor valor geral
d2D.min()

3

In [44]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([17, 16,  5,  5,  5, 14, 45, 14, 26,  3])

In [45]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([3, 5, 5, 5, 9])

In [46]:
# Retorna o maior valor geral
d2D.max()

94

In [47]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([59, 78, 89, 93, 31, 93, 94, 40, 80, 88])

In [48]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([85, 93, 78, 93, 94])

In [49]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  43,   59,  103,  182,  188,  273,  344,  358,  438,  441,  460,
        477,  482,  506,  516,  609,  680,  710,  760,  802,  819,  897,
        903,  908,  918,  949, 1007, 1025, 1088, 1126, 1185, 1207, 1296,
       1389, 1394, 1408, 1453, 1485, 1511, 1532, 1550, 1615, 1624, 1640,
       1671, 1704, 1798, 1838, 1874, 1962], dtype=int32)

In [50]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 43,  16,  44,  79,   6,  85,  71,  14,  80,   3],
       [ 62,  33,  49, 103,  16, 178, 142,  44, 130,  45],
       [ 79, 111,  55, 108,  26, 209, 200,  62, 193,  83],
       [138, 133, 144, 201,  31, 223, 245,  94, 219, 104],
       [156, 198, 153, 217,  62, 256, 339, 134, 255, 192]], dtype=int32)

In [51]:
d2D

array([[43, 16, 44, 79,  6, 85, 71, 14, 80,  3],
       [19, 17,  5, 24, 10, 93, 71, 30, 50, 42],
       [17, 78,  6,  5, 10, 31, 58, 18, 63, 38],
       [59, 22, 89, 93,  5, 14, 45, 32, 26, 21],
       [18, 65,  9, 16, 31, 33, 94, 40, 36, 88]])

In [52]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 43,  59, 103, 182, 188, 273, 344, 358, 438, 441],
       [ 19,  36,  41,  65,  75, 168, 239, 269, 319, 361],
       [ 17,  95, 101, 106, 116, 147, 205, 223, 286, 324],
       [ 59,  81, 170, 263, 268, 282, 327, 359, 385, 406],
       [ 18,  83,  92, 108, 139, 172, 266, 306, 342, 430]], dtype=int32)

In [53]:
# Retorna a média aritmética
d2D.mean()

39.24

In [54]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([31.2, 39.6, 30.6, 43.4, 12.4, 51.2, 67.8, 26.8, 51. , 38.4])

In [55]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([44.1, 36.1, 32.4, 40.6, 43. ])

In [56]:
# Retorna o desvio padrão
d2D.std()

28.40250693160729

In [57]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([16.95169608, 26.44692799, 32.61042778, 35.57864528,  9.52050419,
       31.66322788, 16.26530049,  9.5163018 , 19.16246331, 28.38732111])

In [58]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([31.21041493, 26.78227025, 24.69493875, 29.04892425, 28.14604768])

In [59]:
# Retorna a mediana (geral)
np.median(d2D)

31.5

In [60]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([19., 22.,  9., 24., 10., 33., 71., 30., 50., 38.])

In [61]:
# Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([43.5, 27. , 24.5, 29. , 34.5])

### Copiando e concatenando arrays

In [62]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[11, 37, 42, 30, 33],
       [21, 27,  5,  6, 34],
       [ 6,  5, 48, 21, 12],
       [ 7,  6, 30, 48, 18]])

In [63]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[60, 58, 60, 78, 94],
       [70, 66, 64, 69, 67],
       [77, 75, 60, 74, 95],
       [72, 72, 79, 68, 65]])

In [64]:
c2D = a2D
c2D

array([[11, 37, 42, 30, 33],
       [21, 27,  5,  6, 34],
       [ 6,  5, 48, 21, 12],
       [ 7,  6, 30, 48, 18]])

In [65]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[-1, 37, 42, 30, 33],
       [21, 27, -1, -1, 34],
       [-1, -1, 48, 21, -1],
       [-1, -1, 30, 48, -1]])

In [66]:
a2D 

array([[-1, 37, 42, 30, 33],
       [21, 27, -1, -1, 34],
       [-1, -1, 48, 21, -1],
       [-1, -1, 30, 48, -1]])

Os elementos de a2D também foram alterados. :-(

In [67]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[41,  5, 21, 35, 48],
       [46, 23, 23, 27, 17],
       [39, 19, 34, 26, 15],
       [12, 14, 45, 26, 15]])

In [68]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[41,  5, 21, 35, 48],
       [46, 23, 23, 27, 17],
       [39, 19, 34, 26, 15],
       [12, 14, 45, 26, 15]])

In [69]:
c2D[c2D < 20] = -1
c2D

array([[41, -1, 21, 35, 48],
       [46, 23, 23, 27, -1],
       [39, -1, 34, 26, -1],
       [-1, -1, 45, 26, -1]])

In [70]:
a2D

array([[41,  5, 21, 35, 48],
       [46, 23, 23, 27, 17],
       [39, 19, 34, 26, 15],
       [12, 14, 45, 26, 15]])

Agora sim!!!

### Ordenando os elementos de um array

In [71]:
a1D = np.random.randint(1,100, 15)
a1D

array([20, 53, 95, 13, 89, 87, 87, 80, 16, 22, 37,  2, 90, 34, 48])

In [72]:
a1D.sort()
a1D

array([ 2, 13, 16, 20, 22, 34, 37, 48, 53, 80, 87, 87, 89, 90, 95])

In [73]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[74, 24, 94, 64, 27, 51, 13, 89, 25, 72],
       [66, 48, 12, 14, 84, 66, 16, 68, 87, 53],
       [41, 27, 61, 83, 31, 17, 10,  1, 12, 61],
       [72, 20, 43, 65, 26,  9, 77, 92,  4, 87],
       [18, 25,  3, 34, 27, 35, 66, 46,  6, 71],
       [16,  2, 64, 59, 16, 11, 48, 79, 63, 54]])

In [74]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[13, 24, 25, 27, 51, 64, 72, 74, 89, 94],
       [12, 14, 16, 48, 53, 66, 66, 68, 84, 87],
       [ 1, 10, 12, 17, 27, 31, 41, 61, 61, 83],
       [ 4,  9, 20, 26, 43, 65, 72, 77, 87, 92],
       [ 3,  6, 18, 25, 27, 34, 35, 46, 66, 71],
       [ 2, 11, 16, 16, 48, 54, 59, 63, 64, 79]])

In [75]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[ 1,  6, 12, 16, 27, 31, 35, 46, 61, 71],
       [ 2,  9, 16, 17, 27, 34, 41, 61, 64, 79],
       [ 3, 10, 16, 25, 43, 54, 59, 63, 66, 83],
       [ 4, 11, 18, 26, 48, 64, 66, 68, 84, 87],
       [12, 14, 20, 27, 51, 65, 72, 74, 87, 92],
       [13, 24, 25, 48, 53, 66, 72, 77, 89, 94]])

In [76]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[30, 96,  4, 79, 24, 94, 21, 98, 63, 50],
       [82, 86,  9, 24, 65, 12, 63, 63, 74, 59],
       [48, 58, 92,  9, 66, 61, 28, 58, 83, 67],
       [13,  2,  1, 17, 96, 57, 94, 30, 16, 44],
       [18, 54, 91, 54, 13, 84, 99, 57, 20, 92],
       [84, 23,  5, 44, 75, 48, 74, 23, 20, 12]])

In [77]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[ 4, 21, 24, 30, 50, 63, 79, 94, 96, 98],
       [ 9, 12, 24, 59, 63, 63, 65, 74, 82, 86],
       [ 9, 28, 48, 58, 58, 61, 66, 67, 83, 92],
       [ 1,  2, 13, 16, 17, 30, 44, 57, 94, 96],
       [13, 18, 20, 54, 54, 57, 84, 91, 92, 99],
       [ 5, 12, 20, 23, 23, 44, 48, 74, 75, 84]])

### Transposição de arrays

In [78]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [80]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [82]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Mudando o formato de um array - reshape()

In [83]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [84]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(24,)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [85]:
a2D_4x6 = a1D.reshape(4,6)
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [86]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [87]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [88]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [89]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [90]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[91, 39, 99, 80, 59, 54, 77, 62,  6],
       [ 6, 88, 31, 68, 53, 66, 40, 58,  2],
       [93, 99, 70, 80, 34, 11, 20, 22, 66]])

In [91]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[48, 49, 42, 85, 83, 90, 50, 44, 24],
       [89, 24, 47, 88,  3, 49, 58, 98, 98],
       [61,  5, 15, 10, 47, 97, 77,  8, 16],
       [32, 22, 55, 29, 45,  1, 63, 21, 78],
       [69, 63, 77, 42, 25, 74,  6,  6, 66]])

In [92]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[ 82,   2,   6,   9],
       [ 21,   9,  73,  71],
       [ 59,   8,  20,  79],
       [ 56,  77,  75,  54],
       [ 68,  13,  63, 100]])

In [93]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [94]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [95]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

a2D
[[91 39 99 80 59 54 77 62  6]
 [ 6 88 31 68 53 66 40 58  2]
 [93 99 70 80 34 11 20 22 66]]

b2D
[[48 49 42 85 83 90 50 44 24]
 [89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]

Concatenação
[[91 39 99 80 59 54 77 62  6]
 [ 6 88 31 68 53 66 40 58  2]
 [93 99 70 80 34 11 20 22 66]
 [48 49 42 85 83 90 50 44 24]
 [89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]


In [96]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

a2D
[[91 39 99 80 59 54 77 62  6]
 [ 6 88 31 68 53 66 40 58  2]
 [93 99 70 80 34 11 20 22 66]]

b2D
[[48 49 42 85 83 90 50 44 24]
 [89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]

Concatenação
[[91 39 99 80 59 54 77 62  6]
 [ 6 88 31 68 53 66 40 58  2]
 [93 99 70 80 34 11 20 22 66]
 [48 49 42 85 83 90 50 44 24]
 [89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]


In [97]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

b2D
[[48 49 42 85 83 90 50 44 24]
 [89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]

c2D
[[ 82   2   6   9]
 [ 21   9  73  71]
 [ 59   8  20  79]
 [ 56  77  75  54]
 [ 68  13  63 100]]

Concatenação
[[ 48  49  42  85  83  90  50  44  24  82   2   6   9]
 [ 89  24  47  88   3  49  58  98  98  21   9  73  71]
 [ 61   5  15  10  47  97  77   8  16  59   8  20  79]
 [ 32  22  55  29  45   1  63  21  78  56  77  75  54]
 [ 69  63  77  42  25  74   6   6  66  68  13  63 100]]


In [98]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

b2D
[[48 49 42 85 83 90 50 44 24]
 [89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]

c2D
[[ 82   2   6   9]
 [ 21   9  73  71]
 [ 59   8  20  79]
 [ 56  77  75  54]
 [ 68  13  63 100]]

Concatenação
[[ 48  49  42  85  83  90  50  44  24  82   2   6   9]
 [ 89  24  47  88   3  49  58  98  98  21   9  73  71]
 [ 61   5  15  10  47  97  77   8  16  59   8  20  79]
 [ 32  22  55  29  45   1  63  21  78  56  77  75  54]
 [ 69  63  77  42  25  74   6   6  66  68  13  63 100]]


### Dividindo arrays

In [100]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

Array original
[[91 39 99 80 59 54 77 62  6]
 [ 6 88 31 68 53 66 40 58  2]
 [93 99 70 80 34 11 20 22 66]
 [48 49 42 85 83 90 50 44 24]
 [89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]

1a parte
[[91 39 99 80 59 54 77 62  6]
 [ 6 88 31 68 53 66 40 58  2]
 [93 99 70 80 34 11 20 22 66]
 [48 49 42 85 83 90 50 44 24]]

2a parte
[[89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]


In [101]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])

Array original
[[91 39 99 80 59 54 77 62  6]
 [ 6 88 31 68 53 66 40 58  2]
 [93 99 70 80 34 11 20 22 66]
 [48 49 42 85 83 90 50 44 24]
 [89 24 47 88  3 49 58 98 98]
 [61  5 15 10 47 97 77  8 16]
 [32 22 55 29 45  1 63 21 78]
 [69 63 77 42 25 74  6  6 66]]

1a parte
[[91 39 99]
 [ 6 88 31]
 [93 99 70]
 [48 49 42]
 [89 24 47]
 [61  5 15]
 [32 22 55]
 [69 63 77]]

2a parte
[[80 59 54]
 [68 53 66]
 [80 34 11]
 [85 83 90]
 [88  3 49]
 [10 47 97]
 [29 45  1]
 [42 25 74]]

3a parte
[[77 62  6]
 [40 58  2]
 [20 22 66]
 [50 44 24]
 [58 98 98]
 [77  8 16]
 [63 21 78]
 [ 6  6 66]]
